package edu.gatech;

public enum EventType {

	ADD_BUS,EXTEND_BUS_ROUTE,ADD_RIDER,ADD_TRAIN,EXTEND_TRAIN_ROUTE,TRAIN_STOP_SCHEDULE,BUS_STOP_SCHEDULE,ADD_BUS_STOP,ADD_TRAIN_STOP,ADD_BUS_ROUTE,ADD_TRAIN_ROUTE,
	SYSTEM_REPORT,STEP_EVENT_ONCE,STEP_EVENT_MULTI,EVENT_FOR_TIME;
}


